### ISSUE TITLE
Installation wizard

### ISSUE THREAD

**Issue by stefaniuk** [qnap-dev/container-apps#43]
I would like to make my application TCP port configurable and let user decide its number in the wizard. Here is my `docker-compose.yml` file:

```
version: '2'
services:
  web:
    image: portainer/portainer:1.12.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    command:
      - --bind $PORTAINER_BIND
```

How should I implement it in the `wizard/install.json` file so the PORTAINER_BIND variable can be defined by a user during the installation process?
